#!/usr/bin/env node

/**
 * Quick integration test for the PricePulse auth endpoints.
 * Usage:
 *   node scripts/test-signup.mjs --api=https://api.example.com --password='Test1234!' --username=demo123
 *
 * Required args:
 *   --api            Base API endpoint (e.g. https://xxxx.execute-api.us-east-1.amazonaws.com)
 *
 * Optional args:
 *   --username       Username to register (defaults to autogenerated)
 *   --email          Email to use (defaults to <username>@example.test)
 *   --password       Password to use (defaults to Test1234!)
 */

const argv = process.argv.slice(2);
const options = {
  api: process.env.PRICEPULSE_API_ENDPOINT,
  username: undefined,
  email: undefined,
  password: process.env.PRICEPULSE_TEST_PASSWORD,
};

for (const arg of argv) {
  const [key, value] = arg.split("=", 2);
  if (!key.startsWith("--")) continue;
  const normalizedKey = key.slice(2);
  if (Object.prototype.hasOwnProperty.call(options, normalizedKey)) {
    options[normalizedKey] = value ?? "";
  }
}

if (!options.api) {
  console.error("Error: Missing --api argument or PRICEPULSE_API_ENDPOINT env var.");
  process.exit(1);
}

const username = options.username || `codex-test-${Date.now()}`;
const email = options.email || `${username}@example.test`;
const password = options.password || "Test1234!";

const baseUrl = options.api.replace(/\/$/, "");

async function call(endpoint, payload) {
  const response = await fetch(`${baseUrl}${endpoint}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  let data = {};
  try {
    data = await response.json();
  } catch (error) {
    console.error("Failed to parse JSON response", error);
  }

  if (!response.ok) {
    const message = data?.message || response.statusText;
    throw new Error(`${response.status} ${message}`);
  }

  return data;
}

console.log(`➤ Testing signup for ${username} (${email})`);

try {
  const signupResult = await call("/auth/signup", {
    username,
    email,
    password,
  });
  console.log("  ✓ Signup response:", signupResult);

  const signinResult = await call("/auth/signin", {
    username,
    password,
  });
  console.log("  ✓ Signin response contains tokens:", {
    accessToken: !!signinResult.accessToken,
    idToken: !!signinResult.idToken,
    refreshToken: !!signinResult.refreshToken,
  });

  console.log("✅ Auth flow works end-to-end");
} catch (error) {
  console.error("❌ Auth test failed:", error.message);
  process.exit(1);
}
